### ISSUE TITLE
Running in Docker on OSX

### ISSUE THREAD

**Issue by Shinoby1992** [syuchan1005/OSX-KVM#1]
I created the HighSierra ISO and put in in a Folder.
then:
docker run --privileged --name macOS --device /dev/kvm:/dev/kvm -p 1234:5900 -v /Users/blabla/Desktop/HighSierra:/data syuchan1005/osx-kvm

```
### copy files from iso
*stdin*:1: libguestfs: error: file receive cancelled by daemon
*stdin*:1: libguestfs: error: tar subprocess failed: tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
### cleaning up ...
Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize KVM: No such file or directory
```

**Comment by syuchan1005** [comment]
@Shinoby1992
I think your machine is not support kvm or not enabled kvm.

Steps in enable kvm
1. Enable Intel VT-x or AMD-V in UEFI.
2. Install kvm in your host machine.
3. 'sudo modprobe kvm', 'sudo modprobe kvm-{your cpu(ex. intel, amd)}' do in terminal.

**Comment by Shinoby1992** [comment]
im running it on a mac and osx installed not on linux. and i have kvm enabled (yes its possible to enable it on macosx)

**Comment by syuchan1005** [comment]
@Shinoby1992
I have no idea.
The folder of kvm of macOS may be different.

**Comment by stevefan1999-personal** [comment]
You can't. OSX kernel runs a mix of FreeBSD and Mach (Darwin) and so you don't have KVM on OSX. Bhyve however is supported.
